"""charger_slots

Revision ID: 9eb127d372b3
Revises: 
Create Date: 2024-03-18 11:50:57.436427

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eb127d372b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charger_slots',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('number', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('api_address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('sent_to_customer', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charger_slots_api_address'), 'charger_slots', ['api_address'], unique=False)
    op.create_index(op.f('ix_charger_slots_number'), 'charger_slots', ['number'], unique=False)
    op.create_index(op.f('ix_charger_slots_price'), 'charger_slots', ['price'], unique=False)
    op.create_index(op.f('ix_charger_slots_status'), 'charger_slots', ['status'], unique=False)
    op.create_index(op.f('ix_charger_slots_type'), 'charger_slots', ['type'], unique=False)
    op.create_index(op.f('ix_charger_slots_updated_at'), 'charger_slots', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charger_slots_updated_at'), table_name='charger_slots')
    op.drop_index(op.f('ix_charger_slots_type'), table_name='charger_slots')
    op.drop_index(op.f('ix_charger_slots_status'), table_name='charger_slots')
    op.drop_index(op.f('ix_charger_slots_price'), table_name='charger_slots')
    op.drop_index(op.f('ix_charger_slots_number'), table_name='charger_slots')
    op.drop_index(op.f('ix_charger_slots_api_address'), table_name='charger_slots')
    op.drop_table('charger_slots')
    # ### end Alembic commands ###
